source "https://rubygems.org"

gem "run_loop", github: "calabash/run_loop", branch: develop
gem "awesome_print", "~> 1.8"
gem "pry-byebug", "~> 3.6"
gem "rspec_junit_formatter", "~> 0.3"
gem "rspec", "~> 3.0"
gem "guard-rspec", "~> 4.0"
gem "terminal-notifier", "~> 2.0"
gem "terminal-notifier-guard", "~> 1.0"
gem "guard-bundler", "~> 2.0"
